"""
Market-data provider with graceful offline fallback.

Primary source is yfinance (live Yahoo Finance data). When the network is
unavailable or a symbol cannot be resolved, the provider transparently falls
back to a *deterministic* synthetic series generated by geometric Brownian
motion seeded from the symbol. This keeps the whole platform fully functional
offline and during demos, while using real prices whenever possible.

Every public method is defensive: it never raises on a data failure, it
degrades to synthetic data and flags ``is_synthetic``.
"""
from __future__ import annotations

import hashlib
from datetime import datetime, timedelta
from typing import Optional

import numpy as np
import pandas as pd

try:
    import yfinance as yf
    _YF_AVAILABLE = True
except Exception:                       # pragma: no cover - import guard
    _YF_AVAILABLE = False


class MarketData:
    """Cached market-data access with a synthetic fallback."""

    def __init__(self, use_live: bool = True):
        self.use_live = use_live and _YF_AVAILABLE
        self._price_cache: dict = {}
        self._hist_cache: dict = {}
        self.synthetic_symbols: set = set()    # symbols served from fallback

    # ------------------------------------------------------------------ #
    #  Deterministic synthetic generators (offline fallback)
    # ------------------------------------------------------------------ #
    @staticmethod
    def _seed(symbol: str) -> int:
        h = hashlib.md5(symbol.encode()).hexdigest()
        return int(h[:8], 16)

    def _synthetic_history(self, symbol: str, days: int = 504) -> pd.DataFrame:
        """GBM price path, reproducible per symbol."""
        rng = np.random.default_rng(self._seed(symbol))
        start_price = 50 + (self._seed(symbol) % 450)      # 50 - 500
        mu, sigma = 0.08 / 252, 0.20 / np.sqrt(252)         # daily drift / vol
        shocks = rng.normal(mu, sigma, days)
        path = start_price * np.exp(np.cumsum(shocks))
        idx = pd.bdate_range(end=datetime.today(), periods=days)
        return pd.DataFrame({"Close": path}, index=idx)

    # ------------------------------------------------------------------ #
    #  Price history
    # ------------------------------------------------------------------ #
    def history(self, symbol: str, period: str = "2y") -> pd.DataFrame:
        """Daily close history. Returns a DataFrame indexed by date with a
        ``Close`` column. Falls back to synthetic data on any failure."""
        if symbol in self._hist_cache:
            return self._hist_cache[symbol]

        df = None
        if self.use_live:
            try:
                raw = yf.Ticker(symbol).history(period=period, auto_adjust=True)
                if raw is not None and not raw.empty and "Close" in raw:
                    df = raw[["Close"]].copy()
                    df.index = df.index.tz_localize(None)
            except Exception:
                df = None

        if df is None or df.empty:
            df = self._synthetic_history(symbol)
            self.synthetic_symbols.add(symbol)

        self._hist_cache[symbol] = df
        return df

    # ------------------------------------------------------------------ #
    #  Spot price (latest close)
    # ------------------------------------------------------------------ #
    def spot(self, symbol: str) -> float:
        if symbol in self._price_cache:
            return self._price_cache[symbol]
        df = self.history(symbol)
        price = float(df["Close"].iloc[-1])
        self._price_cache[symbol] = price
        return price

    def previous_close(self, symbol: str) -> float:
        """Prior day's close (for daily P&L)."""
        df = self.history(symbol)
        if len(df) >= 2:
            return float(df["Close"].iloc[-2])
        return float(df["Close"].iloc[-1])

    # ------------------------------------------------------------------ #
    #  Returns helpers (for risk analytics)
    # ------------------------------------------------------------------ #
    def returns(self, symbol: str, period: str = "1y") -> pd.Series:
        df = self.history(symbol, period)
        return df["Close"].pct_change().dropna()

    def spot_map(self, symbols) -> dict:
        """Convenience: {symbol: spot} for a collection of symbols."""
        return {s: self.spot(s) for s in set(symbols)}

    def is_synthetic(self, symbol: str) -> bool:
        return symbol in self.synthetic_symbols
